name: vnt_hrm
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.1
  shared_preferences: ^0.5.6
  equatable: ^1.0.0
  flutter_bloc: ^3.1.0
  meta: ^1.1.6
  json_annotation: ^3.0.0
  intl: ^0.16.0
  simple_gesture_detector: ^0.1.3
  flutter_spinkit: ^4.1.1+1
  flutter_datetime_picker: 1.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/iconMenu.png
    - images/iconNews.png
    - images/qrCode.png
    - images/logoVnt.png
    - images/background.png
    - images/picture2.png
    - images/iconCalender.png
    - images/iconTool.png
    - images/job.png
    - images/leaving.png
    - images/salary.png
    - images/money.png
    - images/Avatar_home.png
    - images/backround_home.png
    - images/Label_home.png
    - images/menu_home.png
    - images/bot_calendar.png
    - images/bot_home.png
    - images/bot_qrcode.png
    - images/bot_tool.png
    - images/3.0x/backround_home@3x.png
    - images/2.0x/backround_home@2x.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
